spring:
  rabbitmq:
    host: localhost
    password: test
    port: 5672
    username: user
    exchange: user.exchange
    queue: test.queue
    routingKey: user.routingkey
  activemq:
    packages:
      trust-all: true
      trusted: com.example.batchrabbitamqphome.domain.MessageTemplate